### PR TITLE
[fluent] style migration: visual state scheme migration

### PR DESCRIPTION
**Pull request by Sanlorng**
1. ButtonColorScheme
2. CheckBoxColorScheme
3. MenuItemColorScheme
4. RadioButtonStyleScheme
5. NavigationItemColorScheme, `NavigationItem.Indicator` and `NavigationDefaults.VerticalIndicator`
6. SwitcherStyleScheme
7. TextFieldColorScheme, `TextField.placeholder`, `TextFieldDefaults.DecorationBox`

### CODE REVIEW

**Comment by Konyaco** [comment]
I simplified the implementation, there is no need to over-design for just a simple function. Furthermore, TextField has different state detection logic compared to other components.

**Comment by Sanlorng** [comment]
> I simplified the implementation, there is no need to over-design for just a simple function. Furthermore, TextField has different state detection logic compared to other components.

VisualState as Sealed interface ，because we can create sub-class called `VisualState.Custom` that make Visual State customizable ，we can use this function implementation AdaptiveTrigger Api，which

**Comment by Sanlorng** [comment]
> > > I simplified the implementation, there is no need to over-design for just a simple function. Furthermore, TextField has different state detection logic compared to other components.
> > 
> > VisualState as Sealed interface ，because we can create sub-class called `VisualState.Custom` that make Visual State customizable ，we can use this function implementation AdaptiveTrigger Api
> 
> What is AdaptiveTrigger

In my prototype，VisualState and VisualStateScheme was similar with XAML VisualState and VisualStateManager，
We can define control goto any visual state, and apply target scheme，define actual scheme by implement VisualStateScheme

**Comment by Konyaco** [comment]
> > > > I simplified the implementation, there is no need to over-design for just a simple function. Furthermore, TextField has different state detection logic compared to other components.
> > > 
> > > 
> > > VisualState as Sealed interface ，because we can create sub-class called `VisualState.Custom` that make Visual State customizable ，we can use this function implementation AdaptiveTrigger Api
> > 
> > 
> > What is AdaptiveTrigger
> 
> In my prototype，VisualState and VisualStateScheme was similar with XAML VisualState and VisualStateManager， We can define control goto any visual state, and apply target scheme，define actual scheme by implement VisualStateScheme

Our code is based on [Fluent Design Guidance](https://www.figma.com/community/file/1159947337437047524), not WinUI Library. Compose framework is much more flexible than XAML, there is no need to pre-declare any rules. So, it's not our goal to provide the same API as XAML. Instead, we aim to provide similar API usage to the Material Design library, because there are many similar concepts between these design systems. We should avoid introducing new concepts, especially the ones not in the Fluent Design System.

**Pull request merged**
