### PR TITLE
Added WASM, JS and iOS support

### PR DESCRIPTION
**Pull request by terrakok**
Run:
 - Wasm `./gradlew :gallery:wasmJsBrowserRun`
 - JS `./gradlew :gallery:jsBrowserRun`
 - iOS open `iosApp/iosApp.xcodeproj` in Xcode and ckick the run button

image

image

### CODE REVIEW

**Comment by terrakok** [comment]
Now you can publish the web demo as a github static page 🤘

**Comment by terrakok** [comment]
JS is here as well 🌈
image

**Comment by terrakok** [comment]
JS is here as well 🌈 
image

**Review by Konyaco — APPROVED** [review]

**Comment by Konyaco** [comment]
Thank you so much! 😁

**Comment by Sanlorng** [comment]
> Now you can publish the web demo as a github static page 🤘
Thank you for your contribution. We have now deployed it to GitHub Pages. 
https://konyaco.github.io/compose-fluent-ui/

**Pull request merged**
