### PR TITLE
[Gallery] update UI

### PR DESCRIPTION
**Pull request by Sanlorng**
1. Support open component source code link and sample code link.
2. Support inverse theme in the sample display area.
3. Support sample options and outputs.
image
4. Add `TypographyScreen`
image
5. Add `IconsScreen`
image

### CODE REVIEW

**Comment by Konyaco** [comment]
image
It doesn't seem to work on my computer?

**Comment by Sanlorng** [comment]
> image It doesn't seem to work on my computer?

I tested it at another computer, it dosen't works too. i will try make it work again.

**Comment by Sanlorng** [comment]
I force push the branch that revert the mica effect workaround. could you test and review the branch?

**Comment by Konyaco** [comment]
> I force push the branch that revert the mica effect workaround. could you test and review the branch again?

All right, I have tested it.

**Comment by Sanlorng** [comment]
> > I force push the branch that revert the mica effect workaround. could you test and review the branch again?
> 
> All right, I have tested it.

it means i can merge it to the `dev` branch now?

**Review by Konyaco — APPROVED** [review]

**Pull request merged**
